### ISSUE TITLE
Issue in @vercel\git-hooks 

### ISSUE THREAD

**Issue by SmitPatel-TCTG** [bigcommerce/nextjs-commerce#42]
`{
  "private": true,
  "packageManager": "yarn@1.22.21",
  "engines": {
    "node": ">=18",
    "yarn":">=1"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint-staged": "lint-staged",
    "prettier": "prettier --write --ignore-unknown .",
    "prettier:check": "prettier --check --ignore-unknown .",
    "test": "pnpm lint && pnpm prettier:check"
  },
  "git": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*": "prettier --write --ignore-unknown"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "clsx": "^2.0.0",
    "geist": "^1.0.0",
    "next": "14.0.0",
    "react": "18.2.0",
    "react-cookie": "^4.1.1",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@tailwindcss/container-queries": "^0.1.1",
    "@tailwindcss/typography": "^0.5.10",
    "@types/node": "20.8.9",
    "@types/react": "18.2.33",
    "@types/react-dom": "18.2.14",
    "@vercel/git-hooks": "^1.0.0",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.52.0",
    "eslint-config-next": "^14.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-unicorn": "^48.0.1",
    "lint-staged": "^15.0.2",
    "postcss": "^8.4.31",
    "prettier": "3.0.3",
    "prettier-plugin-tailwindcss": "^0.5.6",
    "tailwindcss": "^3.3.5",
    "typescript": "5.2.2"
  }
}`

error C:\src\dev\vercel-2\node_modules\@vercel\git-hooks: Command failed.
Exit code: 1
Command: node ./install.js
Arguments:
Directory: C:\src\dev\vercel-2\node_modules\@vercel\git-hooks
Output:
△  @vercel/git-hooks: installing base hook to C:\src\dev\vercel-2\.git\hooks

node:fs:1811
  binding.symlink(
          ^

Error: EPERM: operation not permitted, symlink '.\_do_hook.cjs' -> 'C:\src\dev\vercel-2\.git\hooks\applypatch-msg'
    at Object.symlinkSync (node:fs:1811:11)
    at installHook (C:\src\dev\vercel-2\node_modules\@vercel\git-hooks\install.js:122:5)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\src\dev\vercel-2\node_modules\@vercel\git-hooks\install.js:146:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
  path: '.\\_do_hook.cjs',
  dest: 'C:\\src\\dev\\vercel-2\\.git\\hooks\\applypatch-msg'
}
<img width="782" alt="image" src="https://github.com/bigcommerce/nextjs-commerce/assets/141918345/f2f6a74e-7be0-477f-9061-bfeef1af6cbe">

Getting error during yarn install. Any idea how to resolve this issue.

**Comment by SmitPatel-TCTG** [comment]
Thanks @seyfi-ab  it's fixed my issue
